export interface LocationProduct {
  slug: string;
  title: string;
  shortTitle: string;
  category: string;
  href: string;
  quoteProduct: string;
  image: string;
  description: string;
  localIntent: string;
  bestFor: string;
}

export const LOCATION_PRODUCTS: LocationProduct[] = [
  {
    slug: "curtains",
    title: "Custom Curtains",
    shortTitle: "Curtains",
    category: "Curtains",
    href: "/curtains",
    quoteProduct: "Curtains",
    image: "/assets/curtain_hero.png",
    description: "Made-to-measure curtains for soft privacy, insulation, room darkening and a more finished interior.",
    localIntent: "We bring curtain fabrics, heading options and track advice to your home so you can compare them in your own light.",
    bestFor: "Bedrooms, living rooms, sliding doors and full-height windows",
  },
  {
    slug: "sheer-curtains",
    title: "Sheer Curtains",
    shortTitle: "Sheers",
    category: "Curtains",
    href: "/curtains/sheer",
    quoteProduct: "Sheer Curtains",
    image: "/images/product-unique/mcb-sheer-curtains-soft-light-hero.webp",
    description: "Soft sheer curtains for daytime privacy, filtered light and a lighter, more elegant room feel.",
    localIntent: "We help you choose sheer fabrics, fullness and tracks that suit the room, outlook and privacy level.",
    bestFor: "Street-facing living areas and rooms that need soft daylight",
  },
  {
    slug: "blockout-curtains",
    title: "Blockout Curtains",
    shortTitle: "Blockout Curtains",
    category: "Curtains",
    href: "/curtains/blockout",
    quoteProduct: "Blockout Curtains",
    image: "/images/product-unique/mcb-blockout-curtains-bedroom-hero.webp",
    description: "Blockout curtains for privacy, better sleep, thermal comfort and bedrooms that need stronger light control.",
    localIntent: "We measure the window, check return and track options, and recommend fabric weights for the level of darkness you need.",
    bestFor: "Bedrooms, nurseries, media rooms and shift-worker sleep",
  },
  {
    slug: "s-fold-curtains",
    title: "Wavefold Curtains",
    shortTitle: "Wavefold",
    category: "Curtains",
    href: "/curtains/s-fold-curtains",
    quoteProduct: "Wavefold Curtains",
    image: "/images/product-unique/mcb-s-fold-curtains-living-room-hero.webp",
    description: "Wavefold curtains with a consistent wave heading for contemporary homes and large glass spans.",
    localIntent: "We confirm stack space, track position and fabric fullness during your in-home measure.",
    bestFor: "Modern living areas, apartments and wide sliding doors",
  },
  {
    slug: "double-curtains",
    title: "Double Curtains",
    shortTitle: "Double Curtains",
    category: "Curtains",
    href: "/curtains/double-curtains",
    quoteProduct: "Double Curtains",
    image: "/images/product-unique/mcb-double-curtains-hero.webp",
    description: "Double curtains with sheer and blockout layers for day-to-night privacy and softness.",
    localIntent: "We check track layout, stack space and fabric pairings so the two layers work together.",
    bestFor: "Bedrooms, living rooms and day-to-night privacy",
  },
  {
    slug: "gathered-curtains",
    title: "Gathered Curtains",
    shortTitle: "Gathered",
    category: "Curtains",
    href: "/curtains/gathered-curtains",
    quoteProduct: "Gathered Curtains",
    image: "/images/product-unique/mcb-gathered-curtains-hero.webp",
    description: "Gathered curtains for relaxed fullness and a softer heading style.",
    localIntent: "We help you choose fullness, fabric weight and track or rod style for a natural gathered finish.",
    bestFor: "Relaxed bedrooms, living rooms and softer traditional interiors",
  },
  {
    slug: "pleated-curtains",
    title: "Pleated Curtains",
    shortTitle: "Pleated",
    category: "Curtains",
    href: "/curtains/pleated-curtains",
    quoteProduct: "Pleated Curtains",
    image: "/assets/pleated_curtains_hero.png",
    description: "Tailored pleated curtains for a classic, structured and more formal window finish.",
    localIntent: "We help you compare pinch, pencil and box pleat styles against your room and furnishing style.",
    bestFor: "Formal living rooms, bedrooms and traditional interiors",
  },
  {
    slug: "eyelet-curtains",
    title: "Eyelet Curtains",
    shortTitle: "Eyelet",
    category: "Curtains",
    href: "/curtains/eyelet-curtains",
    quoteProduct: "Eyelet Curtains",
    image: "/assets/eyelet_curtains_hero.png",
    description: "Simple eyelet curtains for casual spaces that suit a decorative curtain rod.",
    localIntent: "We advise where eyelets are suitable and where a track or Wavefold heading will work better.",
    bestFor: "Casual bedrooms, family rooms and simple curtain rods",
  },
  {
    slug: "linen-look-curtains",
    title: "Linen-Look Curtains",
    shortTitle: "Linen-Look",
    category: "Curtains",
    href: "/curtains/linen-look",
    quoteProduct: "Linen-Look Curtains",
    image: "/assets/linen_look_curtains_hero.webp",
    description: "Linen-look curtains with relaxed texture and easier-care fabric performance.",
    localIntent: "We bring textured samples so you can see how linen-look fabrics sit against flooring, walls and natural light.",
    bestFor: "Coastal, Scandi, relaxed and warm interior schemes",
  },
  {
    slug: "translucent-curtains",
    title: "Translucent Curtains",
    shortTitle: "Translucent Curtains",
    category: "Curtains",
    href: "/curtains/translucent-curtains",
    quoteProduct: "Translucent Curtains",
    image: "/images/product-unique/mcb-translucent-curtains-light-filtering-hero.webp",
    description: "Translucent curtains for filtered daylight, privacy and softer glare control without full blockout.",
    localIntent: "We bring translucent curtain samples so you can compare glow, privacy and texture in the room itself.",
    bestFor: "Living areas, dining rooms and street-facing rooms that still need daylight",
  },
  {
    slug: "theatre-velvet-curtains",
    title: "Theatre Velvet Curtains",
    shortTitle: "Theatre Velvet",
    category: "Curtains",
    href: "/curtains/theatre-velvet",
    quoteProduct: "Theatre Velvet Curtains",
    image: "/images/product-unique/mcb-theatre-velvet-curtains-media-room-hero.webp",
    description: "Heavy theatre velvet curtains for media rooms, formal spaces, acoustic softness and luxury drape.",
    localIntent: "We confirm fabric weight, track hardware, lining and stack space for a properly supported velvet installation.",
    bestFor: "Home theatres, music rooms, formal rooms and statement bedrooms",
  },
  {
    slug: "motorised-curtains",
    title: "Motorised Curtains",
    shortTitle: "Motorised Curtains",
    category: "Curtains",
    href: "/curtains/motorised",
    quoteProduct: "Motorised Curtains",
    image: "/images/product-unique/mcb-motorised-curtains-hero-track-remote.webp",
    description: "Motorised curtains for remote, app, schedule or voice control on suitable curtain tracks.",
    localIntent: "We check power, span, track type and control preferences during the measure.",
    bestFor: "Wide spans, tall glass, smart homes and hard-to-reach curtains",
  },
  {
    slug: "blinds",
    title: "Custom Blinds",
    shortTitle: "Blinds",
    category: "Blinds",
    href: "/blinds",
    quoteProduct: "Blinds",
    image: "/assets/roller_blind_hero.webp",
    description: "Custom blinds for light, privacy, glare, insulation and day-to-day control in every room.",
    localIntent: "We bring fabric and material samples and advise on the right blind type for each opening.",
    bestFor: "Bedrooms, living rooms, apartments, studies and sliding doors",
  },
  {
    slug: "roller-blinds",
    title: "Roller Blinds",
    shortTitle: "Roller",
    category: "Blinds",
    href: "/blinds/roller-blinds",
    quoteProduct: "Roller Blinds",
    image: "/assets/roller_blinds_interior.png",
    description: "Roller blinds for a clean, compact and practical window finish.",
    localIntent: "We compare blockout, sunscreen, translucent and double roller options in your home.",
    bestFor: "Modern rooms, apartments and cost-effective custom coverage",
  },
  {
    slug: "blockout-blinds",
    title: "Blockout Blinds",
    shortTitle: "Blockout Blinds",
    category: "Blinds",
    href: "/blinds/roller-blinds/blockout",
    quoteProduct: "Blockout Blinds",
    image: "/images/blockout-blinds.png",
    description: "Blockout blinds for privacy, room darkening and simple daily use.",
    localIntent: "We check side gaps, reveal depth and fitting method so expectations around darkness are clear.",
    bestFor: "Bedrooms, nurseries and media rooms",
  },
  {
    slug: "sunscreen-blinds",
    title: "Sunscreen Blinds",
    shortTitle: "Sunscreen",
    category: "Blinds",
    href: "/blinds/roller-blinds/sunscreen",
    quoteProduct: "Sunscreen Blinds",
    image: "/images/sunscreen-blinds.png",
    description: "Sunscreen blinds for glare reduction, UV control and daytime outlook.",
    localIntent: "We help select openness and colour based on privacy, view and sun exposure.",
    bestFor: "Living rooms, studies, west-facing windows and screen glare",
  },
  {
    slug: "double-roller-blinds",
    title: "Double Roller Blinds",
    shortTitle: "Double Roller",
    category: "Blinds",
    href: "/blinds/double-roller-blinds",
    quoteProduct: "Double Roller Blinds",
    image: "/images/double-roller-hero.png",
    description: "Double roller blinds combine sunscreen and blockout fabrics on one opening.",
    localIntent: "We check reveal space and fabric pairing so the two layers operate cleanly.",
    bestFor: "Day and night privacy on the same window",
  },
  {
    slug: "translucent-blinds",
    title: "Translucent Blinds",
    shortTitle: "Translucent",
    category: "Blinds",
    href: "/blinds/translucent-blinds",
    quoteProduct: "Translucent Blinds",
    image: "/images/product-unique/mcb-translucent-blinds-light-filtering-hero.webp",
    description: "Translucent blinds for soft light filtering without fully darkening the room.",
    localIntent: "We show suitable fabrics for privacy, glow and room softness in your own light.",
    bestFor: "Living rooms, dining rooms and soft daytime privacy",
  },
  {
    slug: "honeycomb-blinds",
    title: "Honeycomb Blinds",
    shortTitle: "Honeycomb",
    category: "Blinds",
    href: "/blinds/honeycomb-blinds",
    quoteProduct: "Honeycomb Blinds",
    image: "/images/product-unique/mcb-honeycomb-blinds-clean-energy-efficient-room-hero.webp",
    description: "Honeycomb blinds for insulation, compact stacking and top-down bottom-up privacy options.",
    localIntent: "We recommend cell type, fabric opacity and control options for heat, cold and privacy.",
    bestFor: "Hot windows, cold rooms, street-facing rooms and skylights",
  },
  {
    slug: "venetian-blinds",
    title: "Venetian Blinds",
    shortTitle: "Venetian",
    category: "Blinds",
    href: "/blinds/venetian-blinds",
    quoteProduct: "Venetian Blinds",
    image: "/images/product-unique/mcb-urban-wood-venetian-blinds-hero.webp",
    description: "Venetian blinds for tilt control, airflow and adjustable privacy.",
    localIntent: "We compare timber, PVC composite and aluminium finishes against your room and moisture levels.",
    bestFor: "Kitchens, bathrooms, studies and rooms needing airflow",
  },
  {
    slug: "slimline-aluminium-venetian-blinds",
    title: "Slimline Aluminium Venetian Blinds",
    shortTitle: "Slimline Venetians",
    category: "Blinds",
    href: "/blinds/venetian-blinds/slimline-aluminium",
    quoteProduct: "Slimline Aluminium Venetian Blinds",
    image: "/images/product-unique/mcb-slimline-aluminium-venetians-hero.webp",
    description: "Slimline aluminium Venetian blinds for crisp tilt control, privacy and moisture-resistant performance.",
    localIntent: "We check reveal depth, moisture exposure and slat colour against your frames and room finishes.",
    bestFor: "Bathrooms, kitchens, laundries and compact windows",
  },
  {
    slug: "urban-wood-venetian-blinds",
    title: "Urban Wood Venetian Blinds",
    shortTitle: "Urban Wood Venetians",
    category: "Blinds",
    href: "/blinds/venetian-blinds/urban-wood",
    quoteProduct: "Urban Wood Venetian Blinds",
    image: "/images/product-unique/mcb-urban-wood-venetian-blinds-hero.webp",
    description: "Urban Wood Venetian blinds for timber-look warmth with adjustable light and privacy.",
    localIntent: "We compare finishes and slat widths in your home so the blind works with flooring, cabinetry and wall colour.",
    bestFor: "Bedrooms, living rooms, studies and warmer interior schemes",
  },
  {
    slug: "roman-blinds",
    title: "Roman Blinds",
    shortTitle: "Roman",
    category: "Blinds",
    href: "/blinds/roman-blinds",
    quoteProduct: "Roman Blinds",
    image: "/assets/roman_blinds_closeup.png",
    description: "Roman blinds for a softer fabric finish with a tailored blind function.",
    localIntent: "We help choose fabric, lining and stack position for a neat, furnished look.",
    bestFor: "Bedrooms, formal rooms and feature windows",
  },
  {
    slug: "vertical-blinds",
    title: "Vertical Blinds",
    shortTitle: "Vertical",
    category: "Blinds",
    href: "/blinds/vertical-blinds",
    quoteProduct: "Vertical Blinds",
    image: "/images/product-unique/mcb-vertical-blinds-sliding-door-hero.webp",
    description: "Vertical blinds for large windows and sliding doors that need practical access.",
    localIntent: "We set blade stack direction around door traffic and furniture layout.",
    bestFor: "Sliding doors, rentals and wide glass openings",
  },
  {
    slug: "panel-glide-blinds",
    title: "Panel Glide Blinds",
    shortTitle: "Panel Glide",
    category: "Blinds",
    href: "/blinds/panel-glide",
    quoteProduct: "Panel Glide Blinds",
    image: "/images/product-unique/mcb-panel-glide-blinds-sliding-door-hero.webp",
    description: "Panel glide blinds for wide openings, sliding doors and contemporary panelled coverage.",
    localIntent: "We plan panel width, track layout and stack space before quoting.",
    bestFor: "Large sliding doors, wardrobes and room dividers",
  },
  {
    slug: "motorised-blinds",
    title: "Motorised Blinds",
    shortTitle: "Motorised Blinds",
    category: "Blinds",
    href: "/blinds/motorised-blinds",
    quoteProduct: "Motorised Blinds",
    image: "/images/product-unique/mcb-motorised-blinds-remote-hero.webp",
    description: "Motorised blinds for remote, app, schedule and smart-home control.",
    localIntent: "We check battery or wired options, window size and control preference in person.",
    bestFor: "Large windows, smart homes and hard-to-reach blinds",
  },
  {
    slug: "cassette-blinds",
    title: "Cassette Blinds",
    shortTitle: "Cassette",
    category: "Blinds",
    href: "/blinds/cassette-blinds",
    quoteProduct: "Cassette Blinds",
    image: "/images/product-unique/mcb-cassette-blinds-neat-headbox-hero.webp",
    description: "Cassette blinds with an enclosed headbox for a more integrated roller blind finish.",
    localIntent: "We check reveal depth and hardware clearance before recommending cassette systems.",
    bestFor: "Bedrooms, neat finishes and selected light-gap control needs",
  },
  {
    slug: "skylight-blinds",
    title: "Skylight Blinds",
    shortTitle: "Skylight",
    category: "Blinds",
    href: "/blinds/skylight-blinds",
    quoteProduct: "Skylight Blinds",
    image: "/images/product-unique/mcb-skylight-roof-window-hero.webp",
    description: "Skylight blinds for overhead light, heat and glare control.",
    localIntent: "We assess skylight size, reach and suitable manual or motorised control options.",
    bestFor: "Roof windows, bright rooms and overhead heat control",
  },
  {
    slug: "soft-vertical-drapes",
    title: "Smart Drapes",
    shortTitle: "Smart Drapes",
    category: "Blinds",
    href: "/blinds/soft-vertical-drapes",
    quoteProduct: "Smart Drapes",
    image: "/images/product-unique/mcb-veri-shades-soft-vertical-hero.webp",
    description: "Soft vertical fabric movement for wide openings and sliding doors.",
    localIntent: "We confirm opening width, walk-through use and fabric privacy during your measure.",
    bestFor: "Sliding doors and wide openings needing a softer look",
  },
  {
    slug: "shutters",
    title: "Plantation Shutters",
    shortTitle: "Shutters",
    category: "Shutters",
    href: "/shutters",
    quoteProduct: "Shutters",
    image: "/images/product-unique/mcb-shutters-category-hero.webp",
    description: "Plantation shutters for adjustable light, airflow, privacy and long-term value.",
    localIntent: "We measure each opening and recommend timber, PVC or aluminium based on room use.",
    bestFor: "Street-facing rooms, wet areas, living rooms and long-term upgrades",
  },
  {
    slug: "plantation-shutters",
    title: "Plantation Shutters",
    shortTitle: "Plantation Shutters",
    category: "Shutters",
    href: "/shutters/plantation-shutters",
    quoteProduct: "Plantation Shutters",
    image: "/images/product-unique/mcb-plantation-shutters-range-hero.webp",
    description: "Plantation shutters for a durable, made-to-measure finish with adjustable light, privacy and airflow.",
    localIntent: "We compare timber, PVC and aluminium shutter options after measuring the room, frame and exposure.",
    bestFor: "Street-facing rooms, bedrooms, living areas and premium long-term upgrades",
  },
  {
    slug: "timber-shutters",
    title: "Timber Shutters",
    shortTitle: "Timber",
    category: "Shutters",
    href: "/shutters/plantation-shutters/timber",
    quoteProduct: "Timber Shutters",
    image: "/images/product-unique/mcb-timber-plantation-shutters-hero.webp",
    description: "Timber shutters for natural warmth, texture and premium interior finish.",
    localIntent: "We compare timber finishes and louvre sizes during the home visit.",
    bestFor: "Living rooms, studies and dry interior spaces",
  },
  {
    slug: "polymer-shutters",
    title: "PVC Shutters",
    shortTitle: "PVC",
    category: "Shutters",
    href: "/shutters/plantation-shutters/polymer",
    quoteProduct: "PVC Shutters",
    image: "/images/product-unique/mcb-polymer-shutters-bathroom-hero.webp",
    description: "PVC shutters for wet areas that need a moisture-resistant shutter option.",
    localIntent: "We check moisture exposure and opening size to recommend suitable shutter materials.",
    bestFor: "Bathrooms, kitchens and laundries",
  },
  {
    slug: "aluminium-shutters",
    title: "Aluminium Shutters",
    shortTitle: "Aluminium",
    category: "Shutters",
    href: "/shutters/plantation-shutters/aluminium",
    quoteProduct: "Aluminium Shutters",
    image: "/images/product-unique/mcb-aluminium-shutters-alfresco-hero.webp",
    description: "Aluminium shutters for outdoor rooms, balconies and exposed alfresco areas.",
    localIntent: "We assess weather exposure, fixing points and privacy needs before quoting.",
    bestFor: "Alfresco areas, patios and outdoor privacy",
  },
  {
    slug: "roller-shutters",
    title: "Roller Shutters",
    shortTitle: "Roller Shutters",
    category: "Shutters",
    href: "/shutters/roller-shutters",
    quoteProduct: "Roller Shutters",
    image: "/images/product-unique/mcb-roller-shutters-exterior-window-hero.webp",
    description: "Roller shutters for exterior security, insulation, noise control and strong blockout.",
    localIntent: "We inspect exterior access, window size and control options before recommending a system.",
    bestFor: "Security, shift workers, noise reduction and heat control",
  },
  {
    slug: "security-doors",
    title: "Security Doors",
    shortTitle: "Security Doors",
    category: "Security",
    href: "/security/security-doors",
    quoteProduct: "Security Doors",
    image: "/images/security-door-hero.webp",
    description: "Security doors for stronger entry protection without sacrificing light and airflow.",
    localIntent: "We measure your door, check frame condition and discuss mesh and grille options.",
    bestFor: "Front doors, back doors, airflow and added peace of mind",
  },
  {
    slug: "fly-screens",
    title: "Fly Screens",
    shortTitle: "Fly Screens",
    category: "Security",
    href: "/security/fly-screens",
    quoteProduct: "Fly Screens",
    image: "/images/sec-fly.webp",
    description: "Fly screens for airflow and insect control across windows and doors.",
    localIntent: "We measure screens to fit and advise on standard, retractable and heavier mesh options.",
    bestFor: "Fresh air, insect control, windows, doors and pet-prone openings",
  },
  {
    slug: "pet-mesh",
    title: "Pet Mesh",
    shortTitle: "Pet Mesh",
    category: "Security",
    href: "/security/pet-mesh",
    quoteProduct: "Pet Mesh",
    image: "/images/product-unique/mcb-pet-mesh-installed-hero.webp",
    description: "Pet mesh for stronger airflow and insect-control screens in busy homes.",
    localIntent: "We assess door and window use, pets, traffic and suitable frame options during your measure.",
    bestFor: "Homes with pets, busy doors, airflow and insect control",
  },
  {
    slug: "awnings",
    title: "Outdoor Products",
    shortTitle: "Outdoor",
    category: "Outdoor",
    href: "/awnings",
    quoteProduct: "Outdoor Products",
    image: "/images/product-unique/mcb-outdoor-products-category-hero.webp",
    description: "Outdoor products for heat, shade and a more usable outdoor area.",
    localIntent: "We inspect span, exposure, fixing points and privacy needs before recommending options.",
    bestFor: "Patios, decks, alfresco spaces and hot windows",
  },
  {
    slug: "folding-arm-awnings",
    title: "Folding Arm Awnings",
    shortTitle: "Folding Arm Awnings",
    category: "Outdoor",
    href: "/awnings/folding-arm-awnings",
    quoteProduct: "Folding Arm Awnings",
    image: "/assets/folding_arm_awning.webp",
    description: "Folding arm awnings for retractable patio and deck shade.",
    localIntent: "We check projection, fixing surface, exposure and operation preference during your measure.",
    bestFor: "Patios, decks and outdoor dining shade",
  },
  {
    slug: "straight-drop-awnings",
    title: "Straight Drop Awnings",
    shortTitle: "Straight Drop",
    category: "Outdoor",
    href: "/awnings/straight-drop-awnings",
    quoteProduct: "Straight Drop Awnings",
    image: "/images/product-unique/mcb-straight-drop-awning-hero.webp",
    description: "Straight drop awnings for simple exterior window shade.",
    localIntent: "We assess sun exposure, fixing points and wind before recommending a suitable drop system.",
    bestFor: "Hot windows, sheltered openings, heat and glare control",
  },
  {
    slug: "auto-awnings",
    title: "Auto Awnings",
    shortTitle: "Auto Awnings",
    category: "Outdoor",
    href: "/awnings/auto-awnings",
    quoteProduct: "Auto Awnings",
    image: "/images/product-unique/mcb-auto-awning-hero.webp",
    description: "Auto awnings for classic external heat, glare and privacy control.",
    localIntent: "We assess sun exposure, fixing points and window position before recommending a suitable awning.",
    bestFor: "Hot windows, west-facing rooms, heat and glare control",
  },
  {
    slug: "fixed-guide-awnings",
    title: "Fixed Guide Awnings",
    shortTitle: "Fixed Guide",
    category: "Outdoor",
    href: "/awnings/fixed-guide-awnings",
    quoteProduct: "Fixed Guide Awnings",
    image: "/images/product-unique/mcb-fixed-guide-awning-hero.webp",
    description: "Fixed guide awnings for guided exterior shade and privacy.",
    localIntent: "We check guide suitability, exposure and fixing surfaces before recommending a system.",
    bestFor: "Guided shade, exterior privacy and controlled fabric travel",
  },
  {
    slug: "zipscreens",
    title: "Zipscreens",
    shortTitle: "Zipscreens",
    category: "Outdoor",
    href: "/awnings/zipscreens",
    quoteProduct: "Zipscreens",
    image: "/images/product-unique/mcb-zipscreens-alfresco-hero.webp",
    description: "Zipscreens for track-guided outdoor shade, wind protection and alfresco privacy.",
    localIntent: "We check span, wind exposure and control preference before recommending a system.",
    bestFor: "Alfresco areas, pergolas and outdoor entertaining",
  },
  {
    slug: "motorised-outdoor-blinds",
    title: "Motorised Outdoor Blinds",
    shortTitle: "Motorised Outdoor",
    category: "Outdoor",
    href: "/awnings/motorised-outdoor-blinds",
    quoteProduct: "Motorised Outdoor Blinds",
    image: "/images/product-unique/mcb-motorised-outdoor-blinds-hero.webp",
    description: "Motorised outdoor blinds and awnings for remote alfresco shade.",
    localIntent: "We check power access, exposure and product compatibility before recommending motorisation.",
    bestFor: "Large outdoor openings, convenience and frequent shade adjustment",
  },
  {
    slug: "wire-guide-awnings",
    title: "Wire Guide Awnings",
    shortTitle: "Wire Guide",
    category: "Outdoor",
    href: "/awnings/wire-guide-awnings",
    quoteProduct: "Wire Guide Awnings",
    image: "/images/product-unique/mcb-wire-guide-awning-hero.webp",
    description: "Wire guide awnings for slim guided exterior shade.",
    localIntent: "We check wind, span and fixing points before recommending wire guide or another outdoor option.",
    bestFor: "Slim exterior guidance, windows and sheltered outdoor openings",
  },
  {
    slug: "motorisation",
    title: "Motorisation",
    shortTitle: "Motorisation",
    category: "Motorisation",
    href: "/motorisation",
    quoteProduct: "Motorisation",
    image: "/assets/motorised_rollers.webp",
    description: "Motorisation for blinds, curtains and awnings with remote, app and schedule control.",
    localIntent: "We check power access, product suitability and how you want to control each opening.",
    bestFor: "Smart homes, wide spans, hard-to-reach windows and safer operation",
  },
];

export const FEATURED_LOCATION_PRODUCTS = LOCATION_PRODUCTS.filter((product) =>
  [
    "curtains",
    "sheer-curtains",
    "blockout-curtains",
    "blinds",
    "roller-blinds",
    "blockout-blinds",
    "sunscreen-blinds",
    "honeycomb-blinds",
    "shutters",
    "security-doors",
    "fly-screens",
    "zipscreens",
  ].includes(product.slug)
);

export function getLocationProductBySlug(slug: string) {
  return LOCATION_PRODUCTS.find((product) => product.slug === slug);
}

export function getLocationProductsByCategory(category: string) {
  return LOCATION_PRODUCTS.filter((product) => product.category === category);
}
